//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistenteMatricula.Test.PermisoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Universidad", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Universidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversidadUsuario", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Dominio")]
    [System.SerializableAttribute()]
    public partial class UniversidadUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PermisoService.IPermisoService")]
    public interface IPermisoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadCrear", ReplyAction="http://tempuri.org/IPermisoService/UniversidadCrearResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AsistenteMatricula.Test.PermisoService.RepetidoException), Action="http://tempuri.org/IPermisoService/UniversidadCrearRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Errores")]
        AsistenteMatricula.Test.PermisoService.Universidad UniversidadCrear(AsistenteMatricula.Test.PermisoService.Universidad Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadCrear", ReplyAction="http://tempuri.org/IPermisoService/UniversidadCrearResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad> UniversidadCrearAsync(AsistenteMatricula.Test.PermisoService.Universidad Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadObtener", ReplyAction="http://tempuri.org/IPermisoService/UniversidadObtenerResponse")]
        AsistenteMatricula.Test.PermisoService.Universidad UniversidadObtener(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadObtener", ReplyAction="http://tempuri.org/IPermisoService/UniversidadObtenerResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad> UniversidadObtenerAsync(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadModificar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadModificarResponse")]
        AsistenteMatricula.Test.PermisoService.Universidad UniversidadModificar(AsistenteMatricula.Test.PermisoService.Universidad Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadModificar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadModificarResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad> UniversidadModificarAsync(AsistenteMatricula.Test.PermisoService.Universidad Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadEliminar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadEliminarResponse")]
        void UniversidadEliminar(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadEliminar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadEliminarResponse")]
        System.Threading.Tasks.Task UniversidadEliminarAsync(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadListar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadListarResponse")]
        AsistenteMatricula.Test.PermisoService.Universidad[] UniversidadListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadListar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadListarResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad[]> UniversidadListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioCrear", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioCrearResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AsistenteMatricula.Test.PermisoService.RepetidoException), Action="http://tempuri.org/IPermisoService/UniversidadUsuarioCrearRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Errores")]
        AsistenteMatricula.Test.PermisoService.UniversidadUsuario UniversidadUsuarioCrear(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioCrear", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioCrearResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario> UniversidadUsuarioCrearAsync(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioObtener", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioObtenerResponse")]
        AsistenteMatricula.Test.PermisoService.UniversidadUsuario UniversidadUsuarioObtener(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioObtener", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioObtenerResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario> UniversidadUsuarioObtenerAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioModificar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioModificarResponse")]
        AsistenteMatricula.Test.PermisoService.UniversidadUsuario UniversidadUsuarioModificar(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioModificar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioModificarResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario> UniversidadUsuarioModificarAsync(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioEliminar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioEliminarResponse")]
        void UniversidadUsuarioEliminar(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioEliminar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioEliminarResponse")]
        System.Threading.Tasks.Task UniversidadUsuarioEliminarAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioListar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioListarResponse")]
        AsistenteMatricula.Test.PermisoService.UniversidadUsuario[] UniversidadUsuarioListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPermisoService/UniversidadUsuarioListar", ReplyAction="http://tempuri.org/IPermisoService/UniversidadUsuarioListarResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario[]> UniversidadUsuarioListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPermisoServiceChannel : AsistenteMatricula.Test.PermisoService.IPermisoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PermisoServiceClient : System.ServiceModel.ClientBase<AsistenteMatricula.Test.PermisoService.IPermisoService>, AsistenteMatricula.Test.PermisoService.IPermisoService {
        
        public PermisoServiceClient() {
        }
        
        public PermisoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PermisoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PermisoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PermisoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AsistenteMatricula.Test.PermisoService.Universidad UniversidadCrear(AsistenteMatricula.Test.PermisoService.Universidad Parametro) {
            return base.Channel.UniversidadCrear(Parametro);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad> UniversidadCrearAsync(AsistenteMatricula.Test.PermisoService.Universidad Parametro) {
            return base.Channel.UniversidadCrearAsync(Parametro);
        }
        
        public AsistenteMatricula.Test.PermisoService.Universidad UniversidadObtener(string RUC) {
            return base.Channel.UniversidadObtener(RUC);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad> UniversidadObtenerAsync(string RUC) {
            return base.Channel.UniversidadObtenerAsync(RUC);
        }
        
        public AsistenteMatricula.Test.PermisoService.Universidad UniversidadModificar(AsistenteMatricula.Test.PermisoService.Universidad Parametro) {
            return base.Channel.UniversidadModificar(Parametro);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad> UniversidadModificarAsync(AsistenteMatricula.Test.PermisoService.Universidad Parametro) {
            return base.Channel.UniversidadModificarAsync(Parametro);
        }
        
        public void UniversidadEliminar(string RUC) {
            base.Channel.UniversidadEliminar(RUC);
        }
        
        public System.Threading.Tasks.Task UniversidadEliminarAsync(string RUC) {
            return base.Channel.UniversidadEliminarAsync(RUC);
        }
        
        public AsistenteMatricula.Test.PermisoService.Universidad[] UniversidadListar() {
            return base.Channel.UniversidadListar();
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.Universidad[]> UniversidadListarAsync() {
            return base.Channel.UniversidadListarAsync();
        }
        
        public AsistenteMatricula.Test.PermisoService.UniversidadUsuario UniversidadUsuarioCrear(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro) {
            return base.Channel.UniversidadUsuarioCrear(Parametro);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario> UniversidadUsuarioCrearAsync(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro) {
            return base.Channel.UniversidadUsuarioCrearAsync(Parametro);
        }
        
        public AsistenteMatricula.Test.PermisoService.UniversidadUsuario UniversidadUsuarioObtener(string Correo) {
            return base.Channel.UniversidadUsuarioObtener(Correo);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario> UniversidadUsuarioObtenerAsync(string Correo) {
            return base.Channel.UniversidadUsuarioObtenerAsync(Correo);
        }
        
        public AsistenteMatricula.Test.PermisoService.UniversidadUsuario UniversidadUsuarioModificar(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro) {
            return base.Channel.UniversidadUsuarioModificar(Parametro);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario> UniversidadUsuarioModificarAsync(AsistenteMatricula.Test.PermisoService.UniversidadUsuario Parametro) {
            return base.Channel.UniversidadUsuarioModificarAsync(Parametro);
        }
        
        public void UniversidadUsuarioEliminar(string Correo) {
            base.Channel.UniversidadUsuarioEliminar(Correo);
        }
        
        public System.Threading.Tasks.Task UniversidadUsuarioEliminarAsync(string Correo) {
            return base.Channel.UniversidadUsuarioEliminarAsync(Correo);
        }
        
        public AsistenteMatricula.Test.PermisoService.UniversidadUsuario[] UniversidadUsuarioListar() {
            return base.Channel.UniversidadUsuarioListar();
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.PermisoService.UniversidadUsuario[]> UniversidadUsuarioListarAsync() {
            return base.Channel.UniversidadUsuarioListarAsync();
        }
    }
}
