//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_GestionarUniversidadService.AlumnoSVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/Alumno.Dominio")]
    [System.SerializableAttribute()]
    public partial class Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string universidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                if ((object.ReferenceEquals(this.pinField, value) != true)) {
                    this.pinField = value;
                    this.RaisePropertyChanged("pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string universidad {
            get {
                return this.universidadField;
            }
            set {
                if ((object.ReferenceEquals(this.universidadField, value) != true)) {
                    this.universidadField = value;
                    this.RaisePropertyChanged("universidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObject", Namespace="http://schemas.datacontract.org/2004/07/Alumno.Error")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante[]))]
    public partial class ResultObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumnoSVC.IAlumno")]
    public interface IAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/CrearEstudiante", ReplyAction="http://tempuri.org/IAlumno/CrearEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCF_GestionarUniversidadService.AlumnoSVC.ResultObject), Action="http://tempuri.org/IAlumno/CrearEstudianteResultObjectFault", Name="ResultObject", Namespace="http://schemas.datacontract.org/2004/07/Alumno.Error")]
        WCF_GestionarUniversidadService.AlumnoSVC.Estudiante CrearEstudiante(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/CrearEstudiante", ReplyAction="http://tempuri.org/IAlumno/CrearEstudianteResponse")]
        System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> CrearEstudianteAsync(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ValidarEstudiante", ReplyAction="http://tempuri.org/IAlumno/ValidarEstudianteResponse")]
        WCF_GestionarUniversidadService.AlumnoSVC.Estudiante ValidarEstudiante(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ValidarEstudiante", ReplyAction="http://tempuri.org/IAlumno/ValidarEstudianteResponse")]
        System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> ValidarEstudianteAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ObtenerEstudiante", ReplyAction="http://tempuri.org/IAlumno/ObtenerEstudianteResponse")]
        WCF_GestionarUniversidadService.AlumnoSVC.Estudiante ObtenerEstudiante(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ObtenerEstudiante", ReplyAction="http://tempuri.org/IAlumno/ObtenerEstudianteResponse")]
        System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> ObtenerEstudianteAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ModificarEstudiante", ReplyAction="http://tempuri.org/IAlumno/ModificarEstudianteResponse")]
        WCF_GestionarUniversidadService.AlumnoSVC.Estudiante ModificarEstudiante(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ModificarEstudiante", ReplyAction="http://tempuri.org/IAlumno/ModificarEstudianteResponse")]
        System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> ModificarEstudianteAsync(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ListarEstudiantes", ReplyAction="http://tempuri.org/IAlumno/ListarEstudiantesResponse")]
        WCF_GestionarUniversidadService.AlumnoSVC.Estudiante[] ListarEstudiantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/ListarEstudiantes", ReplyAction="http://tempuri.org/IAlumno/ListarEstudiantesResponse")]
        System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante[]> ListarEstudiantesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumnoChannel : WCF_GestionarUniversidadService.AlumnoSVC.IAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoClient : System.ServiceModel.ClientBase<WCF_GestionarUniversidadService.AlumnoSVC.IAlumno>, WCF_GestionarUniversidadService.AlumnoSVC.IAlumno {
        
        public AlumnoClient() {
        }
        
        public AlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_GestionarUniversidadService.AlumnoSVC.Estudiante CrearEstudiante(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteACrear) {
            return base.Channel.CrearEstudiante(estudianteACrear);
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> CrearEstudianteAsync(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteACrear) {
            return base.Channel.CrearEstudianteAsync(estudianteACrear);
        }
        
        public WCF_GestionarUniversidadService.AlumnoSVC.Estudiante ValidarEstudiante(string usuario) {
            return base.Channel.ValidarEstudiante(usuario);
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> ValidarEstudianteAsync(string usuario) {
            return base.Channel.ValidarEstudianteAsync(usuario);
        }
        
        public WCF_GestionarUniversidadService.AlumnoSVC.Estudiante ObtenerEstudiante(string codigo) {
            return base.Channel.ObtenerEstudiante(codigo);
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> ObtenerEstudianteAsync(string codigo) {
            return base.Channel.ObtenerEstudianteAsync(codigo);
        }
        
        public WCF_GestionarUniversidadService.AlumnoSVC.Estudiante ModificarEstudiante(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteAModificar) {
            return base.Channel.ModificarEstudiante(estudianteAModificar);
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante> ModificarEstudianteAsync(WCF_GestionarUniversidadService.AlumnoSVC.Estudiante estudianteAModificar) {
            return base.Channel.ModificarEstudianteAsync(estudianteAModificar);
        }
        
        public WCF_GestionarUniversidadService.AlumnoSVC.Estudiante[] ListarEstudiantes() {
            return base.Channel.ListarEstudiantes();
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarUniversidadService.AlumnoSVC.Estudiante[]> ListarEstudiantesAsync() {
            return base.Channel.ListarEstudiantesAsync();
        }
    }
}
