//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_GestionarAsistenteService.ValoracionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WCF_ValoracionService.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion))]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaValoracion", Namespace="http://schemas.datacontract.org/2004/07/WCF_ValoracionService.Response")]
    [System.SerializableAttribute()]
    public partial class RespuestaValoracion : WCF_GestionarAsistenteService.ValoracionService.Respuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_GestionarAsistenteService.ValoracionService.Valoracion[] ValoracionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_GestionarAsistenteService.ValoracionService.Valoracion[] Valoraciones {
            get {
                return this.ValoracionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoracionesField, value) != true)) {
                    this.ValoracionesField = value;
                    this.RaisePropertyChanged("Valoraciones");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Valoracion", Namespace="http://schemas.datacontract.org/2004/07/WCF_ValoracionService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Valoracion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_GestionarAsistenteService.ValoracionService.Curso cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_GestionarAsistenteService.ValoracionService.Docente docenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estrellasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal estrellas_promedioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_GestionarAsistenteService.ValoracionService.Sede sedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int alumno {
            get {
                return this.alumnoField;
            }
            set {
                if ((this.alumnoField.Equals(value) != true)) {
                    this.alumnoField = value;
                    this.RaisePropertyChanged("alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCF_GestionarAsistenteService.ValoracionService.Curso curso {
            get {
                return this.cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.cursoField, value) != true)) {
                    this.cursoField = value;
                    this.RaisePropertyChanged("curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCF_GestionarAsistenteService.ValoracionService.Docente docente {
            get {
                return this.docenteField;
            }
            set {
                if ((object.ReferenceEquals(this.docenteField, value) != true)) {
                    this.docenteField = value;
                    this.RaisePropertyChanged("docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int estrellas {
            get {
                return this.estrellasField;
            }
            set {
                if ((this.estrellasField.Equals(value) != true)) {
                    this.estrellasField = value;
                    this.RaisePropertyChanged("estrellas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal estrellas_promedio {
            get {
                return this.estrellas_promedioField;
            }
            set {
                if ((this.estrellas_promedioField.Equals(value) != true)) {
                    this.estrellas_promedioField = value;
                    this.RaisePropertyChanged("estrellas_promedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_creacionField, value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string resenia {
            get {
                return this.reseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.reseniaField, value) != true)) {
                    this.reseniaField = value;
                    this.RaisePropertyChanged("resenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCF_GestionarAsistenteService.ValoracionService.Sede sede {
            get {
                return this.sedeField;
            }
            set {
                if ((object.ReferenceEquals(this.sedeField, value) != true)) {
                    this.sedeField = value;
                    this.RaisePropertyChanged("sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/WCF_ValoracionService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_GestionarAsistenteService.ValoracionService.Docente docenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string aula {
            get {
                return this.aulaField;
            }
            set {
                if ((object.ReferenceEquals(this.aulaField, value) != true)) {
                    this.aulaField = value;
                    this.RaisePropertyChanged("aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCF_GestionarAsistenteService.ValoracionService.Docente docente {
            get {
                return this.docenteField;
            }
            set {
                if ((object.ReferenceEquals(this.docenteField, value) != true)) {
                    this.docenteField = value;
                    this.RaisePropertyChanged("docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string horario {
            get {
                return this.horarioField;
            }
            set {
                if ((object.ReferenceEquals(this.horarioField, value) != true)) {
                    this.horarioField = value;
                    this.RaisePropertyChanged("horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string seccion {
            get {
                return this.seccionField;
            }
            set {
                if ((object.ReferenceEquals(this.seccionField, value) != true)) {
                    this.seccionField = value;
                    this.RaisePropertyChanged("seccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Docente", Namespace="http://schemas.datacontract.org/2004/07/WCF_ValoracionService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Docente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/WCF_ValoracionService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValoracionService.IValoracionService")]
    public interface IValoracionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValoracionService/Registrar", ReplyAction="http://tempuri.org/IValoracionService/RegistrarResponse")]
        WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion Registrar(int idAlumno, int idDocente, int idCurso, int estrellas, string titulo, string resenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValoracionService/Registrar", ReplyAction="http://tempuri.org/IValoracionService/RegistrarResponse")]
        System.Threading.Tasks.Task<WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion> RegistrarAsync(int idAlumno, int idDocente, int idCurso, int estrellas, string titulo, string resenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValoracionService/RankingDocentes", ReplyAction="http://tempuri.org/IValoracionService/RankingDocentesResponse")]
        WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion RankingDocentes(string nombreCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValoracionService/RankingDocentes", ReplyAction="http://tempuri.org/IValoracionService/RankingDocentesResponse")]
        System.Threading.Tasks.Task<WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion> RankingDocentesAsync(string nombreCurso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValoracionServiceChannel : WCF_GestionarAsistenteService.ValoracionService.IValoracionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValoracionServiceClient : System.ServiceModel.ClientBase<WCF_GestionarAsistenteService.ValoracionService.IValoracionService>, WCF_GestionarAsistenteService.ValoracionService.IValoracionService {
        
        public ValoracionServiceClient() {
        }
        
        public ValoracionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValoracionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValoracionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValoracionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion Registrar(int idAlumno, int idDocente, int idCurso, int estrellas, string titulo, string resenia) {
            return base.Channel.Registrar(idAlumno, idDocente, idCurso, estrellas, titulo, resenia);
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion> RegistrarAsync(int idAlumno, int idDocente, int idCurso, int estrellas, string titulo, string resenia) {
            return base.Channel.RegistrarAsync(idAlumno, idDocente, idCurso, estrellas, titulo, resenia);
        }
        
        public WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion RankingDocentes(string nombreCurso) {
            return base.Channel.RankingDocentes(nombreCurso);
        }
        
        public System.Threading.Tasks.Task<WCF_GestionarAsistenteService.ValoracionService.RespuestaValoracion> RankingDocentesAsync(string nombreCurso) {
            return base.Channel.RankingDocentesAsync(nombreCurso);
        }
    }
}
