//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistenteMatricula.Test.GPUniversidadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversidadUsuario", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Dominio")]
    [System.SerializableAttribute()]
    public partial class UniversidadUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GPUniversidadService.IUniversidadUsuarioService")]
    public interface IUniversidadUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Crear", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/CrearResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AsistenteMatricula.Test.GPUniversidadService.RepetidoException), Action="http://tempuri.org/IUniversidadUsuarioService/CrearRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCF_GestionarPermisoService.Errores")]
        AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Crear(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Crear", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/CrearResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario> CrearAsync(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Obtener", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/ObtenerResponse")]
        AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Obtener(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Obtener", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/ObtenerResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario> ObtenerAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Modificar", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/ModificarResponse")]
        AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Modificar(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Modificar", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/ModificarResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario> ModificarAsync(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Eliminar", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/EliminarResponse")]
        void Eliminar(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Eliminar", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Listar", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/ListarResponse")]
        AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversidadUsuarioService/Listar", ReplyAction="http://tempuri.org/IUniversidadUsuarioService/ListarResponse")]
        System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniversidadUsuarioServiceChannel : AsistenteMatricula.Test.GPUniversidadService.IUniversidadUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniversidadUsuarioServiceClient : System.ServiceModel.ClientBase<AsistenteMatricula.Test.GPUniversidadService.IUniversidadUsuarioService>, AsistenteMatricula.Test.GPUniversidadService.IUniversidadUsuarioService {
        
        public UniversidadUsuarioServiceClient() {
        }
        
        public UniversidadUsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniversidadUsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniversidadUsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniversidadUsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Crear(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro) {
            return base.Channel.Crear(Parametro);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario> CrearAsync(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro) {
            return base.Channel.CrearAsync(Parametro);
        }
        
        public AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Obtener(string Correo) {
            return base.Channel.Obtener(Correo);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario> ObtenerAsync(string Correo) {
            return base.Channel.ObtenerAsync(Correo);
        }
        
        public AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Modificar(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro) {
            return base.Channel.Modificar(Parametro);
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario> ModificarAsync(AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario Parametro) {
            return base.Channel.ModificarAsync(Parametro);
        }
        
        public void Eliminar(string Correo) {
            base.Channel.Eliminar(Correo);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(string Correo) {
            return base.Channel.EliminarAsync(Correo);
        }
        
        public AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<AsistenteMatricula.Test.GPUniversidadService.UniversidadUsuario[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
